const projects = [
    {
        slug: 'emcare',
        title: "EMCare - EMC Healthcare",
        description: "EMCare is a digital healthcare application by EMC Healthcare, one of Indonesia's leading private hospital networks, with over 50,000 downloads and a 4.6/5 rating on Google Play. The app enables patients to book appointments, track queues in real-time, access digital medical records, and consult doctors via telemedicine — all in one platform.",
        tech: ['Laravel', 'Flutter', 'Matrix', 'MySQL'],
        image: '/images/emcare.png',
        demo: 'https://play.google.com/store/apps/details?id=id.emc&hl=id',
        detail: '#',
    },
    {
        slug: 'ssa',
        title: "SIER - Super Sport Arena",
        description: 'Super Sport Arena is a mobile application developed for PT Surabaya Industrial Estate Rungkut (SIER) that simplifies sports court booking through a fast, real-time reservation system. Users can browse available schedules, select their preferred time slot, and confirm a booking directly from their phone — no need to call venues or visit in person.',
        tech: ['Laravel', 'Flutter', 'Xendit', 'MySQL'],
        image: '/images/ssa.webp',
        demo: 'https://play.google.com/store/apps/details?id=id.sier.forapp',
        detail: '#',
    },
    {
        slug: 'availra',
        title: "Availra - Online Booking System",
        description: 'Availra is a personal project that I built to explore and solve real-world problems in service booking management. The idea came from observing how many service providers—such as photographers, beauty artists, and small studios—still rely on manual methods like chat messages, spreadsheets, or simple forms to manage their bookings.',
        tech: ['Next.js', 'Tailwind CSS', 'Drizzle ORM', 'Turso'],
        image: '/images/availra.png',
        demo: 'https://availra.com',
        detail: '#',
    },
    {
        slug: 'paymentease',
        title: 'PaymentEase - Elementor Template',
        description: "PaymentEase, a meticulously crafted Elementor Pro template kit designed exclusively for Payment Solutions providers. Powered by WordPress, this template kit leverages the flexibility and robustness of Elementor Pro to deliver a seamless web design experience. With clean lines, intuitive navigation, and strategically placed call-to-actions, PaymentEase ensures a user-friendly interface that instills trust and confidence in your visitors.",
        tech: ['Wordpress', 'Elementor'],
        image: 'https://market-resized.envatousercontent.com/themeforest.net/files/470213741/cover-paymentease.jpg?auto=format&q=94&cf_fit=crop&gravity=top&h=8000&w=590&s=493c363e613888d95af0e5bcfe4540f11bb890393e2d1fcbbe027e9457b316b0',
        demo: 'https://themeforest.net/item/paymentease-payment-solutions-saas-elementor-pro-template-kit/48403778',
        detail: '#',
    },
    {
        slug: 'jaif',
        title: "Japan-ASEAN Integration Fund's Website",
        description: 'The official website of the Japan-ASEAN Integration Fund (JAIF) — an international fund/whitespace established by the Government of Japan within the ASEAN Secretariat to support the integration and development process of the ASEAN Community and to strengthen cooperation between ASEAN and Japan.',
        tech: ['Laravel', 'Livewire', 'MySQL'],
        image: '/images/jaif.png',
        demo: 'https://jaif.asean.org/en',
        detail: '#',
    },
    {
        slug: 'elisa-adhi',
        title: 'ELISA - Adhi Karya',
        description: 'ELISA is a digital procurement platform used by Adhi Karya to manage procurement and auction processes transparently and efficiently. Its goal is to increase transparency, accountability, and effectiveness in procurement between companies and goods/service providers.',
        tech: ['Laravel', 'Jquery', 'MySQL'],
        image: '/images/adhi.png',
        demo: 'https://elisa.adhi.co.id/login',
        detail: '#',
    },
    {
        slug: 'finns',
        title: 'Finns - Back to Bali',
        description: "The website is a major tourism promotion campaign initiated by Finns Beach Club in collaboration with Bali tourism stakeholders to welcome back tourists after the pandemic, promote the island's beauty and attractions, and present major events such as New Year's Eve parties.",
        tech: ['Laravel', 'Jquery', 'MySQL', 'Stripe'],
        image: 'https://finnsbeachclub.com/wp-content/uploads/2023/10/FINNS_DAY-OUT-128.jpg',
        demo: 'https://finnsbeachclub.com/?gclid=Cj0KCQiAyP3KBhD9ARIsAAJLnnbaDH916fR0OM8YwR1kiKFMGaJNJEXHnwIRPtrcqs4nRYgCccwz5DkaAk-LEALw_wcB',
        detail: '#',
    },
    {
        slug: 'alifmart',
        title: 'Alifmart',
        description: 'Alifmart is an e-commerce platform that sells quality fresh agricultural products (vegetables, fruits, etc.) produced by farmers with GAP (Good Agriculture Practices) standards and greenhouse technology, often associated with the Al Ittifaq Islamic Boarding School Cooperative, functioning as a direct-to-consumer (B2C) sales platform and part of an integrated agricultural distribution system.',
        tech: ['Nuxt.js', 'Laravel', 'MySQL'],
        image: '/images/alifmart.png',
        demo: 'https://alifmart.online/',
        detail: '#',
    },
    {
        slug: 'futspots',
        title: 'Futspots',
        description: 'Futspots is a sports technology startup that provides a platform for connecting football, futsal, and mini soccer fans, both individuals and communities, to play together. They actively organize events such as mini soccer tournaments and serve as a platform for the football fan community in Indonesia.',
        tech: ['Laravel', 'Rest API', 'MySQL', 'Xendit'],
        image: '/images/futspots.webp',
        demo: 'https://futspots.com/',
        detail: '#',
    },
    {
        slug: 'uph-mobile',
        title: 'UPH Mobile',
        description: 'UPH Mobile is the official application for Universitas Pelita Harapan (UPH) students. It serves as a digital portal for easy and integrated access to all information about lectures and daily campus activities, from schedules and grades to special program information like MBKM. This application helps students manage their campus experience through a single platform on their mobile phones.',
        tech: ['Laravel', 'Rest API', 'MySQL'],
        image: '/images/uph.png',
        demo: 'https://play.google.com/store/apps/details?id=edu.uph.mobile&hl=id',
        detail: '#',
    },
    {
        slug: 'furist',
        title: 'Furist - Website Template',
        description: "Furist is a modern and minimalist interior & furniture website template designed to showcase clean UI, strong visual hierarchy, and product-focused layouts. This project highlights my ability to build elegant, responsive, and user-centric web interfaces suitable for real-world business use. The design emphasizes simplicity, whitespace, and premium aesthetics, making it ideal for interior brands, furniture catalogs, or landing pages that value clarity and experience.",
        tech: ['React', 'Tailwind CSS', 'Vite'],
        image: '/images/furist.png',
        demo: '/images/furist-fullpage.png',
        detail: 'https://github.com/adimasistiawan/furist-furniture-template',
    },
    {
        slug: 'nero-ai',
        title: 'Nero.AI - Website Template',
        description: "Nero.AI is a conceptual AI SaaS landing page designed to explore modern interface patterns, clean layouts, and scalable product presentation. This project focuses on visual structure, component composition, and user experience",
        tech: ['React', 'Tailwind CSS', 'Vite'],
        image: '/images/nero.png',
        demo: '/images/nero-fullpage.png',
        detail: 'https://github.com/adimasistiawan/nero-ai-template',
    },
]

export default projects